#######################################################
# Reorder a castor simulation from e.g. simulate_tdsse2()
# to the default APE node order
#
# Procedure: 
# 1. prints simulation$tree to a newick file,
#    then reads it back in
#
# 2. Reorders the simulation$tip_states and simulation$node_states to match 
#
# 3. Adds simulation$states, to put all the states in one place
#######################################################
reorder_castor_sim_to_default_ape_node_order <- function(simulation)
	{
	# Make tree table from simulation tree
	simtree = simulation$tree
	simtable = prt(simtree, printflag=FALSE, get_tipnames=TRUE)

	# Write simtree to Newick; read back in to get standard APE newick format
	newtree = read.tree(file="", text=write.tree(simulation$tree, file=""))
	# Write tree table for new tree
	newtable = prt(newtree, printflag=FALSE, get_tipnames=TRUE)

	match_simtree_in_new2 = match(x=newtable$tipnames, table=simtable$tipnames)
	match_simtree_in_new2

	match_simtree_in_new2sub_tips = match_simtree_in_new2[match_simtree_in_new2 <= length(simtree$tip.label)]
	match_simtree_in_new2sub_nodes = match_simtree_in_new2[match_simtree_in_new2 > length(simtree$tip.label)]-length(simtree$tip.label)

	simstates = c(as.numeric(simulation$tip_states), simulation$node_states)

	simstates
	simstates[match_simtree_in_new2]

	simulation$node_states
	simulation$node_states[match_simtree_in_new2sub_nodes]
	
	simulation$tip_states
	simulation$tip_states[match_simtree_in_new2sub_tips]
	
	# Re-save the re-ordered simulation
	simulation2 = simulation
	simulation2$tree = newtree
	simulation2$node_states = simulation$node_states[match_simtree_in_new2sub_nodes]
	simulation2$tip_states = simulation$tip_states[match_simtree_in_new2sub_tips]
	names(simulation2$tip_states) = 1:length(simulation2$tip_states)
	names(simulation2$tip_states)
	simulation2$states = simstates[match_simtree_in_new2]
	return(simulation2)
	} # END reorder_castor_sim_to_default_ape_node_order


# This assumes the list of states can be generated by
# rcpp_areas_list_to_states_list(); a manual states list 
# would need another function
#
# THIS ASSUMES simulation2 = reorder_castor_sim_to_default_ape_node_order(simulation)
# ...HAS BEEN RUN...
plot_castor_simulation <- function(simulation, areas=c("A","B"), max_range_size=2, include_null_range=TRUE)
	{
	defaults='
	areas = c("A", "B")
	max_range_size = 2
	include_null_range = TRUE
	'
	simtree = simulation$tree
	simstates = c(unname(simulation$tip_states), simulation$node_states)
	
	states_list_0based = rcpp_areas_list_to_states_list(areas=areas, maxareas=max_range_size, include_null_range=include_null_range)
	states_list_0based

	possible_ranges_list_txt = areas_list_to_states_list_new(areas=areas,  maxareas=max_range_size, split_ABC=FALSE, include_null_range=include_null_range)
	possible_ranges_list_txt

	# Make the list of ranges by node
	ranges_list = NULL

	for (i in 1:length(states_list_0based))
			{    
			if ( (length(states_list_0based[[i]]) == 1) && (is.na(states_list_0based[[i]])) )
					{
					tmprange = "_"
					} else {
					tmprange = paste(areas[states_list_0based[[i]]+1], collapse="")
					}
			ranges_list = c(ranges_list, tmprange)
			}

	# Look at the ranges list
	ranges_list

	colors_matrix = get_colors_for_numareas(length(areas))
	colors_list_for_states = mix_colors_for_states(colors_matrix, states_list_0based_index=states_list_0based, plot_null_range=include_null_range)
	colors_list_for_states[length(colors_list_for_states)] = "cyan"   # usually "all areas" is white, 
																																			# but with just AB, I like orange

	# Get the colors by node
	statetxt_by_node = rep("_", times=length(simstates))
	for (i in 1:length(statetxt_by_node))
		{
		statetxt_by_node[i] = ranges_list[simstates[i]]
		}
	statetxt_by_node
	
	cols_byNode = rangestxt_to_colors(possible_ranges_list_txt, colors_list_for_states, MLstates=statetxt_by_node)
	cols_byNode

	# Plot the original simtree
	tipnums = 1:length(simtree$tip.label)
	nodenums = (length(simtree$tip.label)+1):(length(simtree$tip.label)+simtree$Nnode)
	plot(simtree, show.tip.label=FALSE)
	axisPhylo()
	mtext(text="Millions of years ago (Mega-annum, Ma)", side=1, line=2.5)
	title("Plotting simtree & states from simulate_tdsse2()")
	tiplabels(text=statetxt_by_node[tipnums], tip=tipnums, bg=cols_byNode[tipnums])
	nodelabels(text=statetxt_by_node[nodenums], node=nodenums, bg=cols_byNode[nodenums])

	return(cols_byNode)
	} # END plot_castor_simulation


default_simfns <- function()
	{
	simfns = c("setup_df.txt",
	"timepoints.txt", 
	"mu_vals_by_t.txt",
	"Qvals_by_t.txt",
	"Crates_by_t.txt",
	"Qarray.txt",
	"Carray.txt")
	return(simfns)
	}


# Simulate for a certain period of time, until minimum number of living taxa produced
starter="
start_state = 2 # number of the starting state
max_simulation_time = 15.0 # Set to 0 if the user doesn't want to set a max simulation time
min_numtaxa = 2
simfns=default_simfns()
seedval = 54321
"
simulate_tdsse2_for_timeperiod <- function(wd, start_state=2, max_simulation_time=10, min_numtaxa=2, simfns=default_simfns(), seedval=54321)
	{
	simfns = get_path_last(simfns)
	
	setwd(wd)
	
	} 














