tree_height
area_names
areas_list
states_list
txt_states_list
max_range_size
include_null_range
root_age_mult
statenums
observed_statenums
numtips
fossil_TF
direct_TF
numstates
numareas
area_of_areas
dmat_base
dmat
dmat_t
jmat_base
jmat
jmat_t
amat_base
amat
amat_t
elist
elist_base
elist_t
dispersal_multipliers_mat
distmat
envdistmat
distmat2
distmat3
maxent01
bmo_rows
d_rows
d_froms
d_tos
d_drows
a_rows
a_froms
a_tos
a_arows
e_rows
gains
losses
j_rows
j_froms
j_tos
j_jrows
j_numdispersals
v_rows
vicdist_base
vicdist
vicdist_t
s_rows
mu_func
max_extinction_rate
multi_area_ranges_have_zero_mu
min_stepsize

tree_height, area_names, areas_list, states_list, txt_states_list, max_range_size, include_null_range, root_age_mult, statenums, observed_statenums, numtips, fossil_TF, direct_TF, numstates, numareas, area_of_areas, dmat_base, dmat, dmat_t, jmat_base, jmat, jmat_t, amat_base, amat, amat_t, elist, elist_base, elist_t, dispersal_multipliers_mat, distmat, envdistmat, distmat2, distmat3, maxent01, bmo_rows, d_rows, d_froms, d_tos, d_drows, a_rows, a_froms, a_tos, a_arows, e_rows, gains, losses, j_rows, j_froms, j_tos, j_jrows, j_numdispersals, v_rows, vicdist_base, vicdist, vicdist_t, s_rows, mu_func, max_extinction_rate, multi_area_ranges_have_zero_mu, min_stepsize, 