
regime
node_state
node_method
node_Lparent_state
node_Rparent_state
root_nodeIndex
numNodes
uppass_edgematrix
thread_for_each_nodeOp
thread_for_each_branchOp
calc_spawn_start
calc_start_time
calc_end_time
calc_duration
calctime_iterations
sampling_f
tipsamp_f
sumLikes_at_node_at_branchTop
lnL_at_node_at_branchTop
lq_at_branchBot
like_at_branchBot
Es_at_each_nodeIndex_branchTop
Es_at_each_nodeIndex_branchBot
fakeX0s_at_each_nodeIndex_branchTop
likes_at_each_nodeIndex_branchTop
normlikes_at_each_nodeIndex_branchTop
likes_at_each_nodeIndex_branchBot
normlikes_at_each_nodeIndex_branchBot
uppass_probs_at_each_nodeIndex_branchBot
anc_estimates_at_each_nodeIndex_branchBot
uppass_probs_at_each_nodeIndex_branchTop
anc_estimates_at_each_nodeIndex_branchTop
fixNodesMult_at_each_nodeIndex_branchBot
fixNodesMult_at_each_nodeIndex_branchTop


regime, node_state, node_method, node_Lparent_state, node_Rparent_state, root_nodeIndex, numNodes, uppass_edgematrix, thread_for_each_nodeOp, thread_for_each_branchOp, calc_spawn_start, calc_start_time, calc_end_time, calc_duration, calctime_iterations, sampling_f, tipsamp_f, sumLikes_at_node_at_branchTop, lnL_at_node_at_branchTop, lq_at_branchBot, like_at_branchBot, Es_at_each_nodeIndex_branchTop, Es_at_each_nodeIndex_branchBot, fakeX0s_at_each_nodeIndex_branchTop, likes_at_each_nodeIndex_branchTop, normlikes_at_each_nodeIndex_branchTop, likes_at_each_nodeIndex_branchBot, normlikes_at_each_nodeIndex_branchBot, uppass_probs_at_each_nodeIndex_branchBot, anc_estimates_at_each_nodeIndex_branchBot, uppass_probs_at_each_nodeIndex_branchTop, anc_estimates_at_each_nodeIndex_branchTop, fixNodesMult_at_each_nodeIndex_branchBot, fixNodesMult_at_each_nodeIndex_branchTop